### ISSUE TITLE
Updated to Springboot 2.0.1 and Vaadin 8.3.1

### ISSUE THREAD

**Issue by henriquemeira** [rolandkrueger/vaadin-by-example#3]
I updated the project source code to Springboot 2.0.1 (vaadin-spring-boot-starter 3.0.0) and Vaadin 8.3.1.

Do you want this update?

**Comment by rolandkrueger** [comment]
Hey @henriquemeira,

thanks a bunch for your contribution! And sorry for the very long delay until you got any answer from me. I must admit that I totally missed your pull request in all that time. I really should pay more attention to my GitHub notification emails.
So thanks for the version update of Spring and Vaadin and for fixing the compilation issues which somehow totally evaded me. 

Cheers!
